<?php 
include "../AirBlade/dao/pdo.php";
include "../AirBlade/dao/hoadon.php";
$NGAYDATHANG = date('d-m-Y H:i:s');
$MASP = $_POST['idsp'];
$iduser = $_POST['iduser'];
$HOTEN = $_POST['HOTEN'];
$DIACHI = $_POST['DIACHI'];
$PHONE = $_POST['SDT'];
$EMAIL = $_POST['email'];
$TONG = $_POST['TONG'];
$PTTT = $_POST['pttt'];
echo $_POST['HOTEN'];
echo "<br>";
echo $_POST['email'];
echo "<br>";
echo $_POST['DIACHI'];
echo "<br>";
echo $_POST['SDT'];
echo "<br>";
echo $_POST['idsp'];
echo "<br>";
echo $_POST['iduser'];
echo "<br>";
echo $_POST['TONG'];
echo "<br>";
echo $_POST['pttt'];
echo "<br>";
echo $NGAYDATHANG;
bill_insert( $MASP , $iduser , $HOTEN , $DIACHI , $PHONE , $EMAIL , $TONG , $PTTT , $NGAYDATHANG );
?>